"""initial: create identity, credential, access_grant, and verification tables

Revision ID: 619400554a58
Revises: 
Create Date: 2026-01-03 13:44:28.674992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619400554a58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=44), nullable=False),
    sa.Column('pda_address', sa.String(length=44), nullable=False),
    sa.Column('owner_pubkey', sa.String(length=44), nullable=False),
    sa.Column('commitment_hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('verification_bits', sa.Integer(), nullable=True),
    sa.Column('recovery_counter', sa.Integer(), nullable=True),
    sa.Column('metadata_uri', sa.String(length=512), nullable=True),
    sa.Column('bump', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_identity_created_at', 'identities', ['created_at'], unique=False)
    op.create_index('idx_identity_pda', 'identities', ['pda_address'], unique=False)
    op.create_index('idx_identity_wallet', 'identities', ['wallet_address'], unique=False)
    op.create_index(op.f('ix_identities_id'), 'identities', ['id'], unique=False)
    op.create_index(op.f('ix_identities_pda_address'), 'identities', ['pda_address'], unique=True)
    op.create_index(op.f('ix_identities_wallet_address'), 'identities', ['wallet_address'], unique=True)
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=128), nullable=False),
    sa.Column('pda_address', sa.String(length=44), nullable=False),
    sa.Column('owner_wallet', sa.String(length=44), nullable=False),
    sa.Column('credential_type', sa.String(length=50), nullable=False),
    sa.Column('claims_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('issuer_did', sa.String(length=128), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('metadata_uri', sa.String(length=512), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('bump', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_wallet'], ['identities.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credential_expiry', 'credentials', ['expiry'], unique=False)
    op.create_index('idx_credential_owner', 'credentials', ['owner_wallet'], unique=False)
    op.create_index('idx_credential_pda', 'credentials', ['pda_address'], unique=False)
    op.create_index('idx_credential_revoked', 'credentials', ['revoked'], unique=False)
    op.create_index('idx_credential_type', 'credentials', ['credential_type'], unique=False)
    op.create_index(op.f('ix_credentials_credential_id'), 'credentials', ['credential_id'], unique=True)
    op.create_index(op.f('ix_credentials_credential_type'), 'credentials', ['credential_type'], unique=False)
    op.create_index(op.f('ix_credentials_id'), 'credentials', ['id'], unique=False)
    op.create_index(op.f('ix_credentials_owner_wallet'), 'credentials', ['owner_wallet'], unique=False)
    op.create_index(op.f('ix_credentials_pda_address'), 'credentials', ['pda_address'], unique=True)
    op.create_index(op.f('ix_credentials_revoked'), 'credentials', ['revoked'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_id', sa.String(length=128), nullable=False),
    sa.Column('wallet_address', sa.String(length=44), nullable=False),
    sa.Column('credential_type', sa.String(length=50), nullable=False),
    sa.Column('overall_status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_address'], ['identities.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verification_created', 'verifications', ['created_at'], unique=False)
    op.create_index('idx_verification_status', 'verifications', ['overall_status'], unique=False)
    op.create_index('idx_verification_type', 'verifications', ['credential_type'], unique=False)
    op.create_index('idx_verification_wallet', 'verifications', ['wallet_address'], unique=False)
    op.create_index(op.f('ix_verifications_credential_type'), 'verifications', ['credential_type'], unique=False)
    op.create_index(op.f('ix_verifications_id'), 'verifications', ['id'], unique=False)
    op.create_index(op.f('ix_verifications_overall_status'), 'verifications', ['overall_status'], unique=False)
    op.create_index(op.f('ix_verifications_verification_id'), 'verifications', ['verification_id'], unique=True)
    op.create_index(op.f('ix_verifications_wallet_address'), 'verifications', ['wallet_address'], unique=False)
    op.create_table('access_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_id', sa.String(length=128), nullable=False),
    sa.Column('pda_address', sa.String(length=44), nullable=False),
    sa.Column('credential_pda', sa.String(length=44), nullable=False),
    sa.Column('grantor_wallet', sa.String(length=44), nullable=False),
    sa.Column('grantee_wallet', sa.String(length=44), nullable=False),
    sa.Column('purpose', sa.String(length=256), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('field_mask', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('bump', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_pda'], ['credentials.pda_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grant_credential', 'access_grants', ['credential_pda'], unique=False)
    op.create_index('idx_grant_expires_at', 'access_grants', ['expires_at'], unique=False)
    op.create_index('idx_grant_grantee', 'access_grants', ['grantee_wallet'], unique=False)
    op.create_index('idx_grant_grantor', 'access_grants', ['grantor_wallet'], unique=False)
    op.create_index('idx_grant_revoked', 'access_grants', ['revoked'], unique=False)
    op.create_index(op.f('ix_access_grants_credential_pda'), 'access_grants', ['credential_pda'], unique=False)
    op.create_index(op.f('ix_access_grants_grant_id'), 'access_grants', ['grant_id'], unique=True)
    op.create_index(op.f('ix_access_grants_grantee_wallet'), 'access_grants', ['grantee_wallet'], unique=False)
    op.create_index(op.f('ix_access_grants_grantor_wallet'), 'access_grants', ['grantor_wallet'], unique=False)
    op.create_index(op.f('ix_access_grants_id'), 'access_grants', ['id'], unique=False)
    op.create_index(op.f('ix_access_grants_pda_address'), 'access_grants', ['pda_address'], unique=True)
    op.create_index(op.f('ix_access_grants_revoked'), 'access_grants', ['revoked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_grants_revoked'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_pda_address'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_grantor_wallet'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_grantee_wallet'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_grant_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_credential_pda'), table_name='access_grants')
    op.drop_index('idx_grant_revoked', table_name='access_grants')
    op.drop_index('idx_grant_grantor', table_name='access_grants')
    op.drop_index('idx_grant_grantee', table_name='access_grants')
    op.drop_index('idx_grant_expires_at', table_name='access_grants')
    op.drop_index('idx_grant_credential', table_name='access_grants')
    op.drop_table('access_grants')
    op.drop_index(op.f('ix_verifications_wallet_address'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_verification_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_overall_status'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_credential_type'), table_name='verifications')
    op.drop_index('idx_verification_wallet', table_name='verifications')
    op.drop_index('idx_verification_type', table_name='verifications')
    op.drop_index('idx_verification_status', table_name='verifications')
    op.drop_index('idx_verification_created', table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_credentials_revoked'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_pda_address'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_owner_wallet'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_credential_type'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_credential_id'), table_name='credentials')
    op.drop_index('idx_credential_type', table_name='credentials')
    op.drop_index('idx_credential_revoked', table_name='credentials')
    op.drop_index('idx_credential_pda', table_name='credentials')
    op.drop_index('idx_credential_owner', table_name='credentials')
    op.drop_index('idx_credential_expiry', table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_identities_wallet_address'), table_name='identities')
    op.drop_index(op.f('ix_identities_pda_address'), table_name='identities')
    op.drop_index(op.f('ix_identities_id'), table_name='identities')
    op.drop_index('idx_identity_wallet', table_name='identities')
    op.drop_index('idx_identity_pda', table_name='identities')
    op.drop_index('idx_identity_created_at', table_name='identities')
    op.drop_table('identities')
    # ### end Alembic commands ###
