"""Add SSO session tables

Revision ID: d62a8fb29ece
Revises: 619400554a58
Create Date: 2026-01-22 21:36:41.894629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62a8fb29ece'
down_revision: Union[str, None] = '619400554a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connected_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=44), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('first_accessed', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identities.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connected_app_name', 'connected_apps', ['app_name'], unique=False)
    op.create_index('idx_connected_app_user', 'connected_apps', ['user_id'], unique=False)
    op.create_index(op.f('ix_connected_apps_app_name'), 'connected_apps', ['app_name'], unique=False)
    op.create_index(op.f('ix_connected_apps_id'), 'connected_apps', ['id'], unique=False)
    op.create_index(op.f('ix_connected_apps_user_id'), 'connected_apps', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=44), nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('auth_method', sa.String(length=20), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identities.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_expires', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_session_revoked', 'sessions', ['is_revoked'], unique=False)
    op.create_index('idx_session_token', 'sessions', ['session_token'], unique=False)
    op.create_index('idx_session_user', 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_is_revoked'), 'sessions', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_is_revoked'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index('idx_session_user', table_name='sessions')
    op.drop_index('idx_session_token', table_name='sessions')
    op.drop_index('idx_session_revoked', table_name='sessions')
    op.drop_index('idx_session_expires', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_connected_apps_user_id'), table_name='connected_apps')
    op.drop_index(op.f('ix_connected_apps_id'), table_name='connected_apps')
    op.drop_index(op.f('ix_connected_apps_app_name'), table_name='connected_apps')
    op.drop_index('idx_connected_app_user', table_name='connected_apps')
    op.drop_index('idx_connected_app_name', table_name='connected_apps')
    op.drop_table('connected_apps')
    # ### end Alembic commands ###
